name: [DISABLED] Deploy Backend to Azure Web App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install root and workspaces (ci)
        working-directory: ezer_dh
        run: |
          npm ci --workspaces
          cd backend && npm ci || true
          cd ../frontend && npm ci || true

      - name: Deploy to Azure Web App (zip root)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ezer_dh


